
'''
2654 ♔ WHITE CHESS KING
2655 ♕ WHITE CHESS QUEEN
2656 ♖ WHITE CHESS ROOK
2657 ♗ WHITE CHESS BISHOP
2658 ♘ WHITE CHESS KNIGHT
2659 ♙ WHITE CHESS PAWN
265A ♚ BLACK CHESS KING
265B ♛ BLACK CHESS QUEEN
265C ♜ BLACK CHESS ROOK
265D ♝ BLACK CHESS BISHOP
265E ♞ BLACK CHESS KNIGHT
265F ♟ BLACK CHESS PAWN
'''
import tkinter as tk

COLUMNAS = 'abcdefgh'
FILAS = '87654321'
PIEZAS = '♜♞♝♛♚♝♞♜'
PEON = '♟'
LADO = 65
LETRA = 'Helvetica'

COLOR_BLANCO = '#dfc07f'
COLOR_NEGRO = '#7a4f37'
COLOR_PIEZA_BLANCA = 'blue'
COLOR_PIEZA_NEGRA = 'black'

cuadro = dict()
escaque = list()


idioma = 'sn'


